# Generated by Django 4.2.3 on 2023-07-20 17:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Brend nomi')),
                ('logo', models.ImageField(upload_to='creators/')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Wear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(default=None, max_length=255, verbose_name='Nomi uz')),
                ('name_ru', models.CharField(default=None, max_length=255, verbose_name='Nomi ru')),
                ('name_en', models.CharField(default=None, max_length=255, verbose_name='Nomi en')),
                ('status', models.IntegerField(choices=[(0, 'YANGI'), (1, 'QABUL QILINGAN'), (2, 'INKOR QILINGAN')], verbose_name='Status')),
                ('description_uz', models.TextField(verbose_name="Ma'lumot uz")),
                ('description_ru', models.TextField(verbose_name="Ma'lumot ru")),
                ('description_en', models.TextField(verbose_name="Ma'lumot en")),
                ('photo', models.ImageField(upload_to='wears/')),
                ('rating_stars', models.IntegerField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('availability', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Narxi')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.brand', verbose_name='Brend')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.category', verbose_name='kategoriya')),
            ],
            options={
                'verbose_name': 'Wear',
                'verbose_name_plural': 'Wears',
            },
        ),
    ]
