# Generated by Django 4.2.3 on 2023-07-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_burger_remove_wear_brand_remove_wear_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burger',
            options={'verbose_name': 'Burger', 'verbose_name_plural': 'Burgers'},
        ),
        migrations.AlterField(
            model_name='burger',
            name='photo',
            field=models.ImageField(upload_to='burgers/'),
        ),
    ]
