# Generated by Django 4.2.3 on 2023-07-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_burger_options_alter_burger_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='show_in_swiper',
            field=models.BooleanField(default=False),
        ),
    ]
