# Generated by Django 4.2.3 on 2023-07-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_burger_show_in_swiper'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(default=None, max_length=255)),
                ('name_ru', models.CharField(default=None, max_length=255)),
                ('name_en', models.CharField(default=None, max_length=255)),
                ('description_uz', models.TextField(verbose_name="Ma'lumot uz")),
                ('description_ru', models.TextField(verbose_name="Ma'lumot ru")),
                ('description_en', models.TextField(verbose_name="Ma'lumot en")),
                ('photo', models.ImageField(upload_to='why/')),
            ],
        ),
    ]
