# Generated by Django 4.2.3 on 2023-07-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_whymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whymodel',
            name='photo',
        ),
    ]
