# Generated by Django 4.2.3 on 2023-07-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_whymodel_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whymodel',
            options={'verbose_name': 'Why', 'verbose_name_plural': 'Why'},
        ),
    ]
