# Generated by Django 4.2.3 on 2023-07-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_whymodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='whymodel',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='why/'),
        ),
    ]
