# Generated by Django 4.2.3 on 2023-07-31 10:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_whymodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='burger',
            name='availability',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burger',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.category', verbose_name='kategoriya'),
        ),
        migrations.AlterField(
            model_name='burger',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name="Ma'lumot en"),
        ),
        migrations.AlterField(
            model_name='burger',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name="Ma'lumot ru"),
        ),
        migrations.AlterField(
            model_name='burger',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Ma'lumot uz"),
        ),
        migrations.AlterField(
            model_name='burger',
            name='name_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='burger',
            name='name_ru',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='burger',
            name='name_uz',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='burger',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='burgers/'),
        ),
        migrations.AlterField(
            model_name='burger',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='burger',
            name='rating_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='burger',
            name='rating_stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='burger',
            name='show_in_swiper',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burger',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'YANGI'), (1, 'QABUL QILINGAN'), (2, 'INKOR QILINGAN')], null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='burger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
