# Generated by Django 4.2.3 on 2023-08-04 10:30

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_burger_added_at_alter_burger_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(default=None, max_length=255)),
                ('name_ru', models.CharField(default=None, max_length=255)),
                ('name_en', models.CharField(default=None, max_length=255)),
                ('description_uz', django_quill.fields.QuillField(verbose_name="Ma'lumot uz")),
                ('description_ru', django_quill.fields.QuillField(verbose_name="Ma'lumot ru")),
                ('description_en', django_quill.fields.QuillField(verbose_name="Ma'lumot en")),
            ],
        ),
    ]
