# Generated by Django 4.2.3 on 2023-08-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='main.category'),
            preserve_default=False,
        ),
    ]
