# Generated by Django 4.2.3 on 2023-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_pagemodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
