# Generated by Django 4.2.3 on 2023-08-09 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_pagemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='available',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
