# Generated by Django 4.2.3 on 2023-08-08 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0018_pagemodel_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.TextField()),
                ('zip', models.CharField(max_length=10)),
                ('total_price', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'YANGI'), (1, 'QABUL QILINGAN'), (2, 'INKOR QILINGAN')], verbose_name='Status')),
                ('payment_status', models.SmallIntegerField(choices=[(0, 'NOANIQ'), (1, 'JARAYONDA'), (2, 'TOLANGAN'), (3, 'BEKOR QILINGAN')])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('burger', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.burger')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.order')),
            ],
        ),
    ]
